// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t * ui_mainScreen;
void ui_event_topBar(lv_event_t * e);
lv_obj_t * ui_topBar;
void ui_event_clock(lv_event_t * e);
lv_obj_t * ui_clock;
void ui_event_filler(lv_event_t * e);
lv_obj_t * ui_filler;
lv_obj_t * ui_batteryBar;
lv_obj_t * ui_batteryPercentage;
lv_obj_t * ui_speedGauge;
lv_obj_t * ui_speed;
lv_obj_t * ui_kmphLabel;
lv_obj_t * ui_infoPanel;
lv_obj_t * ui_motorTempPanel;
lv_obj_t * ui_motorTempLabel;
lv_obj_t * ui_motorTemp;
lv_obj_t * ui_mosfetTempPanel;
lv_obj_t * ui_mosfetTempLabel;
lv_obj_t * ui_mosfetTemp;
lv_obj_t * ui_batteryPanel;
lv_obj_t * ui_batteryLabel;
lv_obj_t * ui_batteryVoltage;
lv_obj_t * ui_dutyPanel;
lv_obj_t * ui_dutyLabel;
lv_obj_t * ui_duty;
lv_obj_t * ui_odoPanel;
void ui_event_odoLabel(lv_event_t * e);
lv_obj_t * ui_odoLabel;
void ui_event_odo(lv_event_t * e);
lv_obj_t * ui_odo;
lv_obj_t * ui_tripPanel;
void ui_event_tripLabel(lv_event_t * e);
lv_obj_t * ui_tripLabel;
void ui_event_trip(lv_event_t * e);
lv_obj_t * ui_trip;
lv_obj_t * ui_maxSpeedPanel;
void ui_event_maxSpeedLabel(lv_event_t * e);
lv_obj_t * ui_maxSpeedLabel;
void ui_event_maxSpeed(lv_event_t * e);
lv_obj_t * ui_maxSpeed;
lv_obj_t * ui_avgSpeedPanel;
void ui_event_avgSpeedLabel(lv_event_t * e);
lv_obj_t * ui_avgSpeedLabel;
void ui_event_avgSpeed(lv_event_t * e);
lv_obj_t * ui_avgSpeed;

// SCREEN: ui_setClockScreen
void ui_setClockScreen_screen_init(void);
lv_obj_t * ui_setClockScreen;
lv_obj_t * ui_Panel3;
void ui_event_backButton(lv_event_t * e);
lv_obj_t * ui_backButton;
lv_obj_t * ui_Label2;
void ui_event_saveClockButton(lv_event_t * e);
lv_obj_t * ui_saveClockButton;
lv_obj_t * ui_Label1;
lv_obj_t * ui_yearPanel;
lv_obj_t * ui_Label6;
lv_obj_t * ui_yearDropdown;
lv_obj_t * ui_monthDropdown;
lv_obj_t * ui_dayDropdown;
lv_obj_t * ui_hourPanel;
lv_obj_t * ui_Label4;
lv_obj_t * ui_hourDropdown;
lv_obj_t * ui_minuteDropdown;
lv_obj_t * ui_secondDropdown;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_topBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_setClockScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
    if(event_code == LV_EVENT_CLICKED) {
        readClockToScreen(e);
    }
}
void ui_event_clock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_setClockScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
    if(event_code == LV_EVENT_CLICKED) {
        readClockToScreen(e);
    }
}
void ui_event_filler(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        readClockToScreen(e);
    }
}
void ui_event_odoLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        odoClicked(e);
    }
}
void ui_event_odo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        odoClicked(e);
    }
}
void ui_event_tripLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        tripClicked(e);
    }
}
void ui_event_trip(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        tripClicked(e);
    }
}
void ui_event_maxSpeedLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        maxSpeedClicked(e);
    }
}
void ui_event_maxSpeed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        maxSpeedClicked(e);
    }
}
void ui_event_avgSpeedLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        avgClicked(e);
    }
}
void ui_event_avgSpeed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        avgClicked(e);
    }
}
void ui_event_backButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_saveClockButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        saveClock(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainScreen_screen_init();
    ui_setClockScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainScreen);
}
