// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t * ui_mainScreen;
void ui_event_topBar(lv_event_t * e);
extern lv_obj_t * ui_topBar;
void ui_event_clock(lv_event_t * e);
extern lv_obj_t * ui_clock;
void ui_event_filler(lv_event_t * e);
extern lv_obj_t * ui_filler;
extern lv_obj_t * ui_batteryBar;
extern lv_obj_t * ui_batteryPercentage;
extern lv_obj_t * ui_speedGauge;
extern lv_obj_t * ui_speed;
extern lv_obj_t * ui_kmphLabel;
extern lv_obj_t * ui_infoPanel;
extern lv_obj_t * ui_motorTempPanel;
extern lv_obj_t * ui_motorTempLabel;
extern lv_obj_t * ui_motorTemp;
extern lv_obj_t * ui_mosfetTempPanel;
extern lv_obj_t * ui_mosfetTempLabel;
extern lv_obj_t * ui_mosfetTemp;
extern lv_obj_t * ui_batteryPanel;
extern lv_obj_t * ui_batteryLabel;
extern lv_obj_t * ui_batteryVoltage;
extern lv_obj_t * ui_dutyPanel;
extern lv_obj_t * ui_dutyLabel;
extern lv_obj_t * ui_duty;
extern lv_obj_t * ui_odoPanel;
void ui_event_odoLabel(lv_event_t * e);
extern lv_obj_t * ui_odoLabel;
void ui_event_odo(lv_event_t * e);
extern lv_obj_t * ui_odo;
extern lv_obj_t * ui_tripPanel;
void ui_event_tripLabel(lv_event_t * e);
extern lv_obj_t * ui_tripLabel;
void ui_event_trip(lv_event_t * e);
extern lv_obj_t * ui_trip;
extern lv_obj_t * ui_maxSpeedPanel;
void ui_event_maxSpeedLabel(lv_event_t * e);
extern lv_obj_t * ui_maxSpeedLabel;
void ui_event_maxSpeed(lv_event_t * e);
extern lv_obj_t * ui_maxSpeed;
extern lv_obj_t * ui_avgSpeedPanel;
void ui_event_avgSpeedLabel(lv_event_t * e);
extern lv_obj_t * ui_avgSpeedLabel;
void ui_event_avgSpeed(lv_event_t * e);
extern lv_obj_t * ui_avgSpeed;
// SCREEN: ui_setClockScreen
void ui_setClockScreen_screen_init(void);
extern lv_obj_t * ui_setClockScreen;
extern lv_obj_t * ui_Panel3;
void ui_event_backButton(lv_event_t * e);
extern lv_obj_t * ui_backButton;
extern lv_obj_t * ui_Label2;
void ui_event_saveClockButton(lv_event_t * e);
extern lv_obj_t * ui_saveClockButton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_yearPanel;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_yearDropdown;
extern lv_obj_t * ui_monthDropdown;
extern lv_obj_t * ui_dayDropdown;
extern lv_obj_t * ui_hourPanel;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_hourDropdown;
extern lv_obj_t * ui_minuteDropdown;
extern lv_obj_t * ui_secondDropdown;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
