// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

void readClockToScreen(lv_event_t * e);
void odoClicked(lv_event_t * e);
void tripClicked(lv_event_t * e);
void maxSpeedClicked(lv_event_t * e);
void avgClicked(lv_event_t * e);
void saveClock(lv_event_t * e);

#endif
