// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include <Arduino.h>
#include <HardwareSerial.h>

#include "WireBus.h"
#include "ui.h"
#include "Vesc.h"

extern Vesc vesc;


void readClockToScreen(lv_event_t* e) {
	// Your code here
	appSerial.println("clock click");
	lv_dropdown_set_selected(ui_yearDropdown, WireBus::year - 2023);
	lv_dropdown_set_selected(ui_monthDropdown, WireBus::month - 1);
	lv_dropdown_set_selected(ui_dayDropdown, WireBus::day - 1);

	lv_dropdown_set_selected(ui_hourDropdown, WireBus::hour);
	lv_dropdown_set_selected(ui_minuteDropdown, WireBus::minute);
	lv_dropdown_set_selected(ui_secondDropdown, WireBus::second);
}

void saveClock(lv_event_t* e) {
	appSerial.println("save clock click");
	lv_calendar_date_t d;
	auto Y = lv_dropdown_get_selected(ui_yearDropdown) + 2023;
	auto M = lv_dropdown_get_selected(ui_monthDropdown) + 1;
	auto D = lv_dropdown_get_selected(ui_dayDropdown) + 1;

	auto h = lv_dropdown_get_selected(ui_hourDropdown);
	auto m = lv_dropdown_get_selected(ui_minuteDropdown);
	auto s = lv_dropdown_get_selected(ui_secondDropdown);
	WireBus::setTime(s, m, h, 1, D, M, Y);
	appSerial.printf("selected date %d-%d-%d %d:%d:%d", Y, M, D, h, m, s);
}

void odoClicked(lv_event_t* e) {
	// Your code here
	appSerial.println("odo click");
	vesc.settings.odo = 0.0;
	vesc.save();
}

void avgClicked(lv_event_t* e) {
	// Your code here
	appSerial.println("avg click");
	vesc.avgSpeed = 0.0;
	vesc.save();
}

void tripClicked(lv_event_t* e) {
	// Your code here
	appSerial.println("trip click");
	vesc.distance = 0.0;
	vesc.save();
}

void maxSpeedClicked(lv_event_t* e) {
	// Your code here
	appSerial.println("max speed click");
	vesc.settings.maxSpeed = 0.0;
	vesc.save();
}