// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_setClockScreen_screen_init(void)
{
    ui_setClockScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setClockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_setClockScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_setClockScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_setClockScreen, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setClockScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_setClockScreen);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x353536), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backButton = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_backButton, 100);
    lv_obj_set_height(ui_backButton, 28);
    lv_obj_set_x(ui_backButton, -101);
    lv_obj_set_y(ui_backButton, -208);
    lv_obj_set_align(ui_backButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backButton, lv_color_hex(0xF25D0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_backButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "BACK");

    ui_saveClockButton = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_saveClockButton, 100);
    lv_obj_set_height(ui_saveClockButton, 28);
    lv_obj_set_x(ui_saveClockButton, -101);
    lv_obj_set_y(ui_saveClockButton, -208);
    lv_obj_set_align(ui_saveClockButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_saveClockButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_saveClockButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_saveClockButton, lv_color_hex(0xF25D0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_saveClockButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_saveClockButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SAVE");

    ui_yearPanel = lv_obj_create(ui_setClockScreen);
    lv_obj_set_height(ui_yearPanel, 50);
    lv_obj_set_width(ui_yearPanel, lv_pct(100));
    lv_obj_set_align(ui_yearPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_yearPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_yearPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_yearPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_yearPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_yearPanel, lv_color_hex(0x353536), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_yearPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_yearPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_yearPanel);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Date");

    ui_yearDropdown = lv_dropdown_create(ui_yearPanel);
    lv_dropdown_set_options(ui_yearDropdown, "2023\n2024\n2025\n2026");
    lv_obj_set_width(ui_yearDropdown, 70);
    lv_obj_set_height(ui_yearDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_yearDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yearDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_yearDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_yearDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_yearDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monthDropdown = lv_dropdown_create(ui_yearPanel);
    lv_dropdown_set_options(ui_monthDropdown, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12");
    lv_obj_set_width(ui_monthDropdown, 70);
    lv_obj_set_height(ui_monthDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_monthDropdown, -59);
    lv_obj_set_y(ui_monthDropdown, 6);
    lv_obj_set_align(ui_monthDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_monthDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_monthDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_monthDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_monthDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dayDropdown = lv_dropdown_create(ui_yearPanel);
    lv_dropdown_set_options(ui_dayDropdown,
                            "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31");
    lv_obj_set_width(ui_dayDropdown, 70);
    lv_obj_set_height(ui_dayDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dayDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dayDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_dayDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dayDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dayDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hourPanel = lv_obj_create(ui_setClockScreen);
    lv_obj_set_height(ui_hourPanel, 50);
    lv_obj_set_width(ui_hourPanel, lv_pct(100));
    lv_obj_set_align(ui_hourPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_hourPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hourPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hourPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_hourPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hourPanel, lv_color_hex(0x353536), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hourPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_hourPanel);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Time");

    ui_hourDropdown = lv_dropdown_create(ui_hourPanel);
    lv_dropdown_set_options(ui_hourDropdown,
                            "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23");
    lv_obj_set_width(ui_hourDropdown, 70);
    lv_obj_set_height(ui_hourDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_hourDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hourDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_hourDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hourDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minuteDropdown = lv_dropdown_create(ui_hourPanel);
    lv_dropdown_set_options(ui_minuteDropdown,
                            "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59");
    lv_obj_set_width(ui_minuteDropdown, 70);
    lv_obj_set_height(ui_minuteDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_minuteDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minuteDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_minuteDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_minuteDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minuteDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondDropdown = lv_dropdown_create(ui_hourPanel);
    lv_dropdown_set_options(ui_secondDropdown,
                            "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59");
    lv_obj_set_width(ui_secondDropdown, 70);
    lv_obj_set_height(ui_secondDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_secondDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_secondDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_secondDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_secondDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_secondDropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backButton, ui_event_backButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_saveClockButton, ui_event_saveClockButton, LV_EVENT_ALL, NULL);

}
